// Seed itinerary for Justin & Ashley · Seoul (Jun 7–11)
// Day 0 = unscheduled "Ideas / swap-in" tray.
window.SEED_ITINERARY = {
  meta: {
    title: "Justin & Ashley · Seoul",
    subtitle: "Jun 7–11 · a food-first trip for Ashley, from Justin",
    center: [37.5563, 126.9869],
    zoom: 12,
    currency: "KRW"
  },
  days: [
    { day: 1, date: "2026-06-07", weekday: "Sun", title: "Arrival → Hongdae & Yeonnam", color: "#c1432c" },
    { day: 2, date: "2026-06-08", weekday: "Mon", title: "Old Seoul: Gwangjang + Euljiro", color: "#34746e" },
    { day: 3, date: "2026-06-09", weekday: "Tue", title: "Seongsu cafés + Seoul Forest → Ikseon BBQ", color: "#3a5a9c" },
    { day: 4, date: "2026-06-10", weekday: "Wed", title: "Markets + seafood feast", color: "#6f4a7c" },
    { day: 5, date: "2026-06-11", weekday: "Thu", title: "Last bites & food souvenirs", color: "#b8893b" },
    { day: 0, date: "", weekday: "", title: "💡 Ideas / swap-in", color: "#8a8275" }
  ],
  stops: [
    // ---------- DAY 1 ----------
    { id: "pungnyeon",  day: 1, order: 1, time: "19:00", type: "bbq",
      name: "Pungnyeon Sutbul Galbi", name_ko: "연남 풍년숯불갈비", area: "Yeonnam-dong",
      lat: 37.5630532, lng: 126.9253417, cost_krw: 35000, place_id: "ChIJjZCiz-6YfDURXdhw0OBS_oo",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipM3MDTyrVdO7cyqBRP-tCsD7iQU5qlHQag0hokO=w800-h600-k-no",
      blurb: "First-night charcoal pork belly & galbi. 5.0★, family-run, real charcoal smokiness. Pair with soju." },
    { id: "hongdae-chimaek", day: 1, order: 2, time: "21:30", type: "bar",
      name: "BBQ Chicken & Beer (Hongdae)", name_ko: "BBQ치킨 홍대로데오점", area: "Hongdae",
      lat: 37.5523919, lng: 126.9213509, cost_krw: 25000, place_id: "ChIJB-rU19qYfDURFwGzBMnK7B8",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF5Wfet6j9nS6KQNrwLWbI_ZE89vvWK-a7gevF5QmteLm_8UVduDEFVFpElgy6nLx4EJIgxe4gGjw8hSCnKLExmfGPHcpxxHABN7_Keh2JMOeKy-jzNtL6O6x_IK9zJxoCDT-uPA4PSj_ru=w800-h600-k-no",
      blurb: "Chimaek nightcap — Korean fried chicken + cold beer, open very late. Any Hongdae chicken+beer spot works." },

    // ---------- DAY 2 ----------
    { id: "eulji-myeonok", day: 2, order: 1, time: "11:30", type: "noodles",
      name: "Eulji Myeonok", name_ko: "을지면옥", area: "Euljiro",
      lat: 37.5736809, lng: 126.9885769, cost_krw: 14000, place_id: "ChIJgamxSgCjfDURXl5INU25Y88",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHWcNMT7h8D9KRC3Hhq1QNWYuORg1i7p2Q7IYsMDIgI5GpPJu9DntoFzUCsI-fz8rE7QIlr83uvt--3LfwwYoCQwzPPasoq9fnhPsRc5v6rIFMxrmgKkHDiHo_3L6HnpCa98yZLQ_oc8vKb=w800-h600-k-no",
      blurb: "Pyongyang-style mul naengmyeon (cold buckwheat noodles). CLOSED SUNDAYS, sells out — arrive by 12:30." },
    { id: "gwangjang", day: 2, order: 2, time: "13:00", type: "market",
      name: "Gwangjang Market", name_ko: "광장시장", area: "Jongno",
      lat: 37.5700398, lng: 126.9996036, cost_krw: 15000, place_id: "ChIJm3V0fu2ifDURRJ8IMUijVtY",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH-TXd-qJ0hLQfDcLOR_s9wLjVRy-uzR7RfpW2iXOxiH9_PQQlKjMTa-YDU7M98ihE9Cv78qzEc_8AJ9guBbm85ugXz20w2AoJ5db2mYMJIVSRzIOoxJf0LBrIFOPASjRQxfmzlZX4OJ80=w800-h600-k-no",
      blurb: "Graze: bindaetteok (mung-bean pancake), mayak gimbap, yukhoe (raw beef), tteokbokki. Cash. Netflix-famous kalguksu too." },
    { id: "manseon-hof", day: 2, order: 3, time: "19:00", type: "bar",
      name: "Manseon Hof (Nogari Alley)", name_ko: "만선호프", area: "Euljiro",
      lat: 37.5671948, lng: 126.991811, cost_krw: 20000, place_id: "ChIJn6hVByKjfDURx-hGevo1qx4",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGssxGNH9MTyH3T3jFBKJ4u0qyIn4SgR5e5N15CMuTTscpR0ZMOepmTH7d-LEfoM-R3Xr99IfFVYwp976gApkZRF0rfWbebpIs7_-eTFfxiCSvMNVEXKdPCYNzLS2do2v2lM2z2gvoJrY9X=w800-h600-k-no",
      blurb: "Euljiro beer-hall alley — dried pollack (nogari) + draft, plastic stools in the street. Vibe + beer, skip the chicken." },

    // ---------- DAY 3 ----------
    { id: "onion-seongsu", day: 3, order: 1, time: "10:00", type: "cafe",
      name: "Cafe Onion Seongsu", name_ko: "어니언 성수", area: "Seongsu-dong",
      lat: 37.5447328, lng: 127.0582091, cost_krw: 12000, place_id: "ChIJHb1ypJWkfDURb2d4XCjLluM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGbw0aYVH-sdUbfATXqONs0Od5RegVYrmzNMnAmNWEIRRDYiGXKjntZTXZGnmojNjNxJDH-VGPiK5KmawJuVGJLnEuW5Ndi6YDf7JWvJ0XRaJIAzZbQv7YT0kUsUrw093xHFaDDimlNk344=w800-h600-k-no",
      blurb: "Brunch in a brutalist former factory. Pandoro + salt bread. Go ~9–10am to beat crowds." },
    { id: "daelim", day: 3, order: 2, time: "12:30", type: "cafe",
      name: "Daelim Changgo", name_ko: "대림창고", area: "Seongsu-dong",
      lat: 37.5418384, lng: 127.0564636, cost_krw: 12000, place_id: "ChIJi_M445OkfDURBV_ePY2qCHo",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF9PMZkJSYL6hJxTIntemAcZNO1Yxp45UXYcMgQYGeIxTO_huAh5JyqnNQk0DXzVtLLpTgpCsi4x9XfAVSyd9k1wj3qhHnkG-RQ-jzpxquQ4xGepl6Xc6GHeYQjaxISqZN3ZdwP=w800-h600-k-no",
      blurb: "Giant red-brick warehouse gallery-café — the icon of Seongsu. Coffee + cake, cinematic industrial space." },
    { id: "seoul-forest", day: 3, order: 3, time: "14:00", type: "park",
      name: "Seoul Forest Park", name_ko: "서울숲", area: "Seongdong-gu",
      lat: 37.5443878, lng: 127.0374424, cost_krw: 0, place_id: "ChIJK_b0UX2jfDURmkYPvmWYm90",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGTEBgUkQU-_V8wPmooQlejFVknGSjDzFwT7tahrZuHrkepXtTdpuw-K9tcdGeGnKVX-DtevG85Bux5X0iBV9wAZ0xWhm515DcEtd2VDwTTgZP0QaWgzLfHuLvQsYONQCk3M67lyw=w800-h600-k-no",
      blurb: "Optional easy stroll to walk off the coffee. Relaxed, not touristy — your one bit of green." },
    { id: "gowoondon", day: 3, order: 4, time: "19:00", type: "bbq",
      name: "Gowoondon (Ikseon-dong BBQ)", name_ko: "고운돈", area: "Ikseon-dong",
      lat: 37.5730622, lng: 126.9899923, cost_krw: 28000, place_id: "ChIJJawtZQCjfDURYKP2MnwsfQk",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipPA3ggQCy5N9Y0fIiX6NqiUUgviWxjydUt4E7RO=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/", reservation_status: "needed",
      blurb: "Hanok-courtyard pork BBQ. 4.9★. Fills fast — arrive ~5–6pm or book via Catch Table. They fry rice/noodles for you at the end." },

    // ---------- DAY 4 ----------
    { id: "tongin", day: 4, order: 1, time: "12:00", type: "market",
      name: "Tongin Market (coin dosirak)", name_ko: "통인시장", area: "Seochon",
      lat: 37.5807649, lng: 126.9706756, cost_krw: 8000, place_id: "ChIJYxd6fL6ifDURy7wm894BUcQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH-VoHyhUy0Ol6O2te7kJdMahoGsvv8n-NfOfeB9xhbMlL---ZoBfG_KnmnT3CmadKrqoDekp7X9iluEGZ8F0f3rjJnKrmt8hVRtPXjUP2njIvmukA-jJYPs6cTj17T1xXCyDiY5KowbRs=w800-h600-k-no",
      blurb: "Buy brass coins, fill a lunch tray from the stalls. Fun and cheap. Closes ~5pm." },
    { id: "tosokchon", day: 4, order: 2, time: "13:30", type: "soup",
      name: "Tosokchon Samgyetang", name_ko: "토속촌 삼계탕", area: "Seochon",
      lat: 37.5777786, lng: 126.9715909, cost_krw: 20000, place_id: "ChIJb5OOGL6ifDURU29ID3t8aOA",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHj6Xu3B1g5hgTJSLwSHAIMmij_j5SX8WcN447mwinTcfOLn4USV_806KRsGbqQTrhHBy3Gcsn35xEHSs4wWoRnMn38lgDUu2YSMP2VGWHkpBfxsLZbfTkGxTOU7H7EHde5kEtHQu66Rm6l=w800-h600-k-no",
      blurb: "5-min walk away — Seoul's famous ginseng chicken soup. Do instead of (or after) Tongin for a sit-down." },
    { id: "noryangjin", day: 4, order: 3, time: "18:30", type: "seafood",
      name: "Noryangjin Fisheries Market", name_ko: "노량진수산시장", area: "Noryangjin",
      lat: 37.5149717, lng: 126.9386342, cost_krw: 50000, place_id: "ChIJOTEaKmiffDURNTst1Jzcm_c",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFoM2OmUrwDpW2KutU8vDjA7RPdGZICzMCcxPaNZFH4iA5lGTtqKrY7TK2yCua0ozPOk17EWnkRx8jOiUnK5DYF4qAPZKU5yBIPYgGYUXg-iqeMHgAdsaxNVTo-A-tmX2he2NRRmBXjwVVe=w800-h600-k-no",
      blurb: "Pick king crab/abalone/sashimi/live octopus downstairs, AGREE PRICE FIRST, eat it cooked upstairs. Cash. The big one." },

    // ---------- DAY 5 ----------
    { id: "london-bagel", day: 5, order: 1, time: "09:00", type: "cafe",
      name: "London Bagel Museum (Anguk)", name_ko: "런던베이글뮤지엄 안국점", area: "Anguk / Bukchon",
      lat: 37.5791826, lng: 126.986152, cost_krw: 12000, place_id: "ChIJKw66zRCjfDURuaw9qYPdI-k",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGYkxb5uafl7vpcRi319FEjpnDxybM-WdQpGXeBqekCzRh2Q_AAwchxNcMN0abgCg1JSrfJs71vO_sc1plbPkf_ApzCrAkTtcEC8OJqN7fs86RjU_VqJH04rPIVL2mx19IwEHsIaOLeTaHP=w800-h600-k-no",
      reservation_url: "https://app.tablemanager.io/", reservation_status: "needed",
      blurb: "Open-run bakery — get on the queue app early, or arrive ~8:30am. Potato-cheese & Bricklane bagels. Onion Anguk is 2 min away." },
    { id: "myeongdong", day: 5, order: 2, time: "18:00", type: "market",
      name: "Myeongdong Night Market", name_ko: "명동 야시장", area: "Myeongdong",
      lat: 37.5616685, lng: 126.9858438, cost_krw: 15000, place_id: "ChIJqb-ne_CifDURR-yH8a3sjXM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH1FH1Gk1_Vi-S-oV7wTJIVSNTEI6ZbwfCSCang9xK_AACIN7Vd1MaPIzF3zFKYiDFI9Kgusr7G1HJ8hVdz48asjcwt7F8lr64ypgxbf_4tt8cOLNWIfnegmpKUb9vGOrmJ5W2zUozxtZ4p=w800-h600-k-no",
      blurb: "Late-flight option: street-food crawl (tornado potato, hotteok, egg bread) + edible souvenirs. Stalls ~5pm+." },

    // ---------- IDEAS / SWAP-IN (day 0) ----------
    { id: "onion-anguk", day: 0, order: 1, time: "", type: "cafe",
      name: "Cafe Onion Anguk", name_ko: "어니언 안국", area: "Anguk / Bukchon",
      lat: 37.5776235, lng: 126.9865541, cost_krw: 12000, place_id: "ChIJLXL2BvijfDURmTrYFPQIGUc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEZ8XDN1sBLm4RNS4WXkpIPhjfJILKicwPXhgfhw34vjHgCzrFX-kYPben5TZcbnMnnIgU6CsmEZ0b11BdbEYeyZKMD6i8cZ5Z8_9S4cf2i4cRuAoHcT0A509N0I9ON3OnaKn9-WIqqiCDT=w800-h600-k-no",
      blurb: "Backup for the Day 5 bagel — hanok-courtyard café, famous pandoro." },
    { id: "jeong-daepo", day: 0, order: 2, time: "", type: "bbq",
      name: "Jeong Daepo (Mapo BBQ)", name_ko: "정대포", area: "Mapo",
      lat: 37.541983, lng: 126.9511176, cost_krw: 30000, place_id: "ChIJqfTTJaeYfDURTvox_bUC6Mk",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGcLcQqUsuQzJdhodAy6QIScs0abIKhrp1clijvTd4WNd5512yMtjGiD4n6-dMDfWuq4Yhg62Ck0612_rVE59RA7Orwf1vQNqOIYCbR_qH9D0ATxp5EpYx-1vcbq43a3Ug23GGikihIOVV7=w800-h600-k-no",
      blurb: "Anthony Bourdain's Mapo charcoal BBQ — egg moat round the grill. Swap into any dinner slot." },
    { id: "mingles", day: 0, order: 3, time: "", type: "splurge", michelin: 3,
      name: "Mingles", name_ko: "밍글스", area: "Cheongdam / Gangnam",
      lat: 37.5253386, lng: 127.0441452, cost_krw: 290000, place_id: "ChIJjXuM24mjfDURSwmouRnxNlM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGE6C8rxjQ0rmFGzxONberjbSVXY5M59rfXGinekid7vqyKJM_61V9P7rKhk1aeTT3f3v11W5fCMGJRX2-g6uskg2PsjbadrfHM1XIToGYKKys5N_6IH-IZFFdBkTEiXtqj0-uqIaGtsfSb=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mingles", reservation_status: "needed",
      unavailable: true,
      blurb: "★★★ Modern Korean tasting menu by Chef Mingoo Kang — the headline splurge. CLOSED Mon & Sun. Currently fully booked; see backups below." },

    // ===== ⭐ MICHELIN-STAR BACKUPS (Seoul & Busan 2026) — Mingles replacements =====
    // cost_krw are rough per-person tasting-menu estimates — edit freely.
    { id: "jungsik", day: 0, order: 22, time: "", type: "splurge", michelin: 2,
      name: "Jungsik Seoul", name_ko: "정식당", area: "Cheongdam / Gangnam",
      lat: 37.5226, lng: 127.0398, cost_krw: 280000, place_id: "",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGu_vHep9cYw2PBAsvQD3jquh5zkTcRHzocL07YO5vldzQ5CFI9W_vJB2HLzyy996Avxt1xUJNQWSl9-V8H7XscU2v4ZHwnqxFHlUw1NP-4AzvgkbMJMxG0BVljA0eDXVOLJuEp=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Jungsik", reservation_status: "needed",
      blurb: "★★ Contemporary Korean — chef Yim Jung-sik's flagship, sister to the NYC outpost. CLOSED Sundays. Sleek, English-friendly." },
    { id: "onjium", day: 0, order: 21, time: "", type: "splurge", michelin: 1,
      name: "Onjium", name_ko: "온지음", area: "Hyoja-dong / Jongno",
      lat: 37.5824, lng: 126.9706, cost_krw: 180000, place_id: "",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAESVV00K9ONDswr-0YErjvG6Ycn-rH7rm5eKY4hpxmraGDcclvQVhkieT9M7jjY9x_37LyH5SAFIrhpAhczsgV8i-aU3eSr2Vk-tAtRt9CpvsWdLQvl3KtburMhSwSUA1ZQSSCkfQ=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Onjium", reservation_status: "needed",
      blurb: "★ Royal Korean cuisine in a quiet hanok, near Gyeongbokgung. CLOSED Sundays. Lunch only — a beautiful, restrained tasting." },

    { id: "la-yeon", day: 0, order: 23, time: "", type: "splurge", michelin: 2,
      name: "La Yeon", name_ko: "라연", area: "The Shilla Seoul (Jung-gu)",
      lat: 37.5557646, lng: 127.0050866, cost_krw: 250000, place_id: "ChIJf8Lq1wSjfDURbuyVUM14Svc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGSzdVWTQVvEFprsHGL1GBPqcQjQrj0APQJwI4wtA_21giqyZS10YRlANdZx4KBLi4e-74-Noo4Cq1MdZeLURoOmn316J1mPGinYEVe0ckiPaGoAdzuNn9CEtmXHFDg4Z6KEswK27DLTHkb=w800-h600-k-no",
      reservation_url: "https://www.shilla.net/seoul/dining/viewDining.do?contentId=la-yeon", reservation_status: "needed",
      blurb: "★★ Korean, on the 23rd floor of The Shilla with Namsan views. OPEN DAILY (lunch+dinner) — a hotel restaurant, so often the easiest 2★ to book last-minute." },
    { id: "mosu", day: 0, order: 24, time: "", type: "splurge", michelin: 2,
      name: "Mosu Seoul", name_ko: "모수", area: "Hannam-dong",
      lat: 37.5411532, lng: 126.9961548, cost_krw: 350000, place_id: "ChIJJeNdcbOjfDURCzyDecCVK7o",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEBwPzNcqHrre7Xxr3SkH7KPmlrxGTMoAO-wjzaSGxPeJ_hc5uSDF-io4gD0kVhcH4HJX6uHIIsnmolkqjnMdclkD0Wr5fp1sujv21OyrYEJTnzZT13sCYVrnnU6QqbiGjYYBBLPAqCvWWe=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mosu", reservation_status: "needed",
      blurb: "★★ Modern Korean by Chef Ahn Sung-jae — Seoul's most acclaimed tasting menu after Mingles. Dinner only, CLOSED Sun & Mon. Hardest to get; try anyway." },
    { id: "alla-prima", day: 0, order: 25, time: "", type: "splurge", michelin: 2,
      name: "Alla Prima", name_ko: "알라프리마", area: "Gangnam (Hakdong)",
      lat: 37.5134138, lng: 127.0260405, cost_krw: 260000, place_id: "ChIJsdM8l_KjfDURobnSNkInVo8",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEG41qAh7Sk0ma4WOOvE5b8rep623KWJOFOMyUXdfBRDn9nTSh0VuLWxN4jjZtRtASKgWu04qQJtfc39FnfrGWUwJW2J6vBILZkHrM0LQvjtKeZs0-ur5ZUG3quG52voHv7nwRtT_TXLjyK=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Alla+Prima", reservation_status: "needed",
      blurb: "★★ Innovative/contemporary, bar seats over a busy open kitchen. CLOSED Tuesdays. Refined, French-leaning technique." },
    { id: "soigne", day: 0, order: 26, time: "", type: "splurge", michelin: 2,
      name: "Soigné", name_ko: "스와니예", area: "Sinsa / Gangnam",
      lat: 37.5193295, lng: 127.0190326, cost_krw: 230000, place_id: "ChIJIU2RrnahfDURNvCJDhODupM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH_F2xWh9iRDkUXLRIURvFcfiNP0s4T1PDVSpDnY4drNE5l0UUDN7O6MM8Qs9ywbeaiZo7-9qc2GPKviLDKRHlkcRp3a1Jt78ae1LTsnOIj8KkJorZIpckL-NLnq1b73fxyNZTu=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Soigne", reservation_status: "needed",
      blurb: "★★ Contemporary Korean-French, famous for its hanwoo. Calm minimalist room. CLOSED Sundays. Lunch is easier to book than dinner." },
    { id: "kwonsooksoo", day: 0, order: 27, time: "", type: "splurge", michelin: 2,
      name: "Kwonsooksoo", name_ko: "권숙수", area: "Apgujeong / Cheongdam",
      lat: 37.5243775, lng: 127.0435589, cost_krw: 290000, place_id: "ChIJZ1-yoYijfDURvkRg_wdaQao",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGqwAtsFKU6aZvPZhSynrbX6QlJkgFj6S-o3iI2CzNvogdkNV2S0ATTnkd701_oenHuTv6gPK9KRG0g0c4EgQNuKHhmfmfEAiALb_mjRBCiDdWE6PFhy8AgqRiZRSJpauwbZl0=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Kwonsooksoo", reservation_status: "needed",
      blurb: "★★ Korean, deeply seasonal with a beloved kimchi cart and 45-year-aged soy. CLOSED Sun & Mon." },
    { id: "mitou", day: 0, order: 28, time: "", type: "splurge", michelin: 2,
      name: "Mitou", name_ko: "미토우", area: "Cheongdam",
      lat: 37.5221974, lng: 127.0450306, cost_krw: 300000, place_id: "ChIJGZ6vIe2jfDURWOUsVCO94cA",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGrDY5RXI-bGkcFjDEHmncJYu636bR3XSSwfkcadejLWdc-DQXyMImtNGhKmOx-pN6j5ywgoe604WJ5lTsn7kJmGJaV9MdPUsU8nOyjdH0WyCjKm7YwcYvzkJ4Khxcsg9oOoeIh=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mitou", reservation_status: "needed",
      blurb: "★★ Intimate Japanese kaiseki, two-chef counter. Dinner only, CLOSED Sun & Mon. Tiny — book the moment a slot opens." },
    { id: "restaurant-allen", day: 0, order: 29, time: "", type: "splurge", michelin: 2,
      name: "Restaurant Allen", name_ko: "레스토랑 알렌", area: "Gangnam (Teheran-ro)",
      lat: 37.5036006, lng: 127.0418041, cost_krw: 260000, place_id: "ChIJQ-Y88belfDURrUsKUS6HMVY",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG9N5eDlVJyZz7gynMaYroB9gA7ZLrJonwjAdTPgJdhVIOl1xEC0zntmvhe8BD5CIWi3Vp0Z2j9IftOGAvv2y4ygVlQrZYx7ufh0-lxW_Cj70zRsFcc3QIxiNcJZCo8tfy9RwE=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Allen", reservation_status: "needed",
      blurb: "★★ Contemporary/French using Korean farm produce, seasonal menu. CLOSED Sun & Mon. Generous, filling courses — a crowd favorite." },
    { id: "sosuheon", day: 0, order: 30, time: "", type: "splurge", michelin: 2,
      name: "Sosuheon", name_ko: "소수헌", area: "Jung-gu (Malli-dong)",
      lat: 37.5529456, lng: 126.9634031, cost_krw: 380000, place_id: "ChIJ6fwnPgCjfDURRK3JXHKApos",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG82IFmZhRaBRQ8gG2DC8wXdM3h3sgIQl3IZR6ayEEMFrVWbEh08qVByHp2oiqG7u6Ae06OGiMSh9y8BXapTlTxFtiF9PZIce3jGTSkZa7sScAMOUBAFOs6rLgm400eIjRHlEuO=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Sosuheon", reservation_status: "needed",
      blurb: "★★ Sushi by Chef Park Kyung-jae in a renovated hanok inside a park. Reservation-only and notoriously hard — long-shot backup but worth a try." },
    { id: "evett", day: 0, order: 31, time: "", type: "splurge", michelin: 2,
      name: "Evett", name_ko: "에빗", area: "Gangnam (Dosan)",
      lat: 37.5233759, lng: 127.0362133, cost_krw: 260000, place_id: "ChIJTaVjWi6hfDURVegqLOB9oSs",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHenaN9tIjz4LooC9mdlPnpBaRKRSEByIraKBeBkzpa7-REi59CuaCKuvSFA6lUBUnQYCGFPMo18F3lFHrAsP0IvRddEFOaD-h6JDzI89wanQCEUXSo_sXXAiH_ne7JvN2oZpLXmg=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Evett", reservation_status: "needed",
      blurb: "★★ Inventive Korean-meets-Australian by Chef Joseph Lidgerwood, with a fun kitchen tour. CLOSED Sun & Mon. English-friendly; juice pairing is great." },

    // ===== 🍢 STREET FOOD (cool picks) — day 0 =====
    { id: "bamdokkaebi", day: 0, order: 32, time: "", type: "streetfood",
      name: "Seoul Bamdokkaebi Night Market (Yeouido)", name_ko: "여의도 밤도깨비 야시장", area: "Yeouido Hangang Park",
      lat: 37.5308271, lng: 126.9283536, cost_krw: 12000, place_id: "ChIJYxvcuRiffDURjo90ImhrJvg",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF8RIrKpG_TGBZ7VBJWrcgOetLfgWIlPb106vedBBIpZw7uqWuv5CbkhOJRd6R4NNN8EZmY1qqC19XYLpwgF4_E5B8azAS8rsO-w1pT_PHvigsBDk3D3iy0uh1IDtj-1C9cYjWh=w800-h600-k-no",
      blurb: "⭐ THE cool one: food trucks along the Han River — eat by the water with a picnic-blanket crowd. WEEKENDS ONLY & seasonal (roughly Fri–Sun eves, spring–autumn). On this trip that's Sun Jun 7 — CHECK the current Hangang/Seoul night-market schedule before counting on it." },
    { id: "jongno-pocha", day: 0, order: 33, time: "", type: "streetfood",
      name: "Jongno 3-ga Pocha Street", name_ko: "종로3가 포장마차 거리", area: "Jongno",
      lat: 37.5702277, lng: 126.9922392, cost_krw: 20000, place_id: "ChIJlcTjXMmjfDURY4e90Feo_dw",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHfQ_pkNxVjrgVwlUKGlyAjYIF8j1Kz37zhr_k8oaH12BZBp9EJfzixFUVPg6A8zFclrM4SEEePJNKSK7qvkH6l2qm7Apvb9UY9tC4DSMU7pJr_ZiMs3dv2FrGkdkWJlXRb-MINwrkgNS0=w800-h600-k-no",
      blurb: "Pojangmacha — orange-tent street stalls at night: seafood pancake, eel, oden, soju, friendly ajummas. Street food + a drink in one. Great late-night near Euljiro/Ikseon (Days 2–3)." },

    // ===== 🍸 BARS (nightcaps) — day 0 =====
    { id: "zest", day: 0, order: 34, time: "", type: "bar",
      name: "Zest", name_ko: "제스트", area: "Cheongdam",
      lat: 37.5252611, lng: 127.0407780, cost_krw: 55000, place_id: "ChIJ9eN6-_GlfDUR5SGWDB7YNkw",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEO_M4c2KwQs7zI3RlUPqtUCtg5Ev5g3_DVZTYF6mJWVvW6608dTHgU67xKjJuWZ0l2fJUgCzUhijst_-jftzz0_-znYRsvCtpUEaAZ6cZfYiPUSDIdZTbUsQFnPDDfq5DuPgHFGQ=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Zest", reservation_status: "needed",
      blurb: "#2 on Asia's 50 Best Bars 2025 — sustainability-driven cocktails, every drink ~₩26k. Tiny & busy; reserve ahead or chance a walk-in. Open daily." },
    { id: "le-chamber", day: 0, order: 35, time: "", type: "bar",
      name: "Le Chamber", name_ko: "르챔버", area: "Cheongdam",
      lat: 37.5262177, lng: 127.0410396, cost_krw: 60000, place_id: "ChIJ639qa3ikfDURlcK_PQa7PbQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFVuc_vQwI8TiU9bpCw2k0uLQnEZuk-QNY-qZprJdOCdAsytCRLdiqGF6XZ4cHoWo57qAGkZaED2S_DkyG-s68gzjy9EeSd2u7NnlT-CykERTSYbv0RFWuLLMDWzZd9Qp92AbQbpb623bg=w800-h600-k-no",
      blurb: "Bookshelf speakeasy — push the right book to get in. Grand-piano glamour, Asia's/World's 50 Best. Open daily, very late." },
    { id: "bar-cham", day: 0, order: 36, time: "", type: "bar",
      name: "Bar Cham", name_ko: "바참", area: "Seochon",
      lat: 37.5791709, lng: 126.9703851, cost_krw: 45000, place_id: "ChIJxWShw9-jfDURS80cyKrrVI4",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipOgzaVroL6GgFco2rzkUwhp2JyT2RYuegUO0fit=w800-h600-k-no",
      blurb: "Cozy cabin bar, cocktails built on Korean ingredients & regions. World's & Asia's 50 Best, famously warm service. CLOSED Tuesdays. Right by Day 4's Seochon." },
    { id: "charles-h", day: 0, order: 37, time: "", type: "bar",
      name: "Charles H.", name_ko: "찰스 H", area: "Gwanghwamun (Four Seasons)",
      lat: 37.5705573, lng: 126.9754314, cost_krw: 60000, place_id: "ChIJfZLLbCOjfDURJv2oIh07atc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG88O2yer2aqC8VVa8M58CJBUiyLLVh5sytJzGvX0ggC3KgTN1eyIsDP7RIWB7kUGT0md95Cvf4PSQCDcr0wb1uUCmCM24OZvNgVY0sLrCUX8K7cXEga5w_wIU-6KrWONpDmsXvtAIhhs44=w800-h600-k-no",
      reservation_url: "https://www.fourseasons.com/seoul/dining/lounges/charles_h/", reservation_status: "needed",
      blurb: "Refined hidden speakeasy inside the Four Seasons — hyper-local Korean cocktails + great bar food. Central, open daily. Easy nightcap near Days 2/5." },
    { id: "saeseoul", day: 0, order: 38, time: "", type: "bar",
      name: "Saeseoul", name_ko: "새서울", area: "Ikseon / Jongno",
      lat: 37.5728113, lng: 126.9898352, cost_krw: 40000, place_id: "ChIJ1x9w99CjfDURbbBhFKdp_8Y",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipN5mwl9AxOXYMMq6QA5diYojfWzSMyEMMl7ZsP2=w800-h600-k-no",
      blurb: "Hidden bar above a retro arcade with a rooftop city view and playful drinks (try the 'Pacman'). Open daily — perfect nightcap after Day 3's Ikseon BBQ." },
    { id: "slow-brew", day: 0, order: 39, time: "", type: "bar",
      name: "Slow Brew Pub (Neurinmaeul)", name_ko: "느린마을 양조장", area: "Gangnam / Seocho",
      lat: 37.498097, lng: 127.0252657, cost_krw: 30000, place_id: "ChIJHbhgd1mhfDURfkpQ0mGQ6sQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAExXvm3hLOro8FmmA57N_u0rQZ7iqcQ1D0Js8ZT4DuZtwYekZ3y5V6IsGjbD5Qavf6dIg3CBUtwriHeXfIxCALP14N16_N7jUkl9PJtsixf2hG2YSQDzLWMf3s4uJkz4jB2S7YbClLFAvsR=w800-h600-k-no",
      blurb: "Makgeolli (rice wine) by the season + jeon pancakes in a modern brewery pub — the traditional-drinking option. Open daily." },

    // ===== 🥩 PREMIUM HANWOO BBQ — day 0 =====
    { id: "insaeng-hanwoo", day: 0, order: 40, time: "", type: "bbq",
      name: "Insaeng Hanwoo", name_ko: "인생한우", area: "Majang / Seongdong-gu",
      lat: 37.57011, lng: 127.0381874, cost_krw: 60000, place_id: "ChIJh5LfCFWjfDURiQ4ty7V9Gqk",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE0vCPzoUUo36cPfRwOnDjekE3uv1Slv3TeZ4zVlLbtlulaaDlV6pHPa3a7c_EDDapvKFGO0K-Y8SkS9cDCSsY7U7CYscjeJ7WU0_PjaSpzaoLbqY9ZuBxwxOD26NCSteapf0OGUFD_0eD1=w800-h600-k-no",
      blurb: "Premium Korean beef (hanwoo) — 1++ grade and 14-day wet-aged, at famously fair prices for the quality, near Majang meat market. Pick your cuts (kkotdeungsim/ribeye is the move); it barely needs the grill. Open daily (break ~2–4:30pm). It's in Seongdong-gu, a short hop from Seoul Forest/Seongsu — a great swap for Day 3's dinner if you'd rather not backtrack to Ikseon." }
  ]
};
