// Seed itinerary for Justin & Ashley · Seoul (Jun 7–11)
// Day 0 = unscheduled "Ideas / swap-in" tray.
window.SEED_ITINERARY = {
  meta: {
    title: "Justin & Ashley · Seoul",
    subtitle: "Jun 7–11 · a food-first trip for Ashley, from Justin",
    center: [37.5563, 126.9869],
    zoom: 12,
    currency: "KRW",
    recipient: "Ashley",
    trip_note: "For Ashley 💛 — you're cute. This is our Seoul eat-tour: a bar waiting every night and way too many backups to argue over. Move anything around and let's make it ours."
  },
  days: [
    { day: 1, date: "2026-06-07", weekday: "Sun", title: "Arrival → Hongdae & Yeonnam", color: "#c1432c" },
    { day: 2, date: "2026-06-08", weekday: "Mon", title: "Old Seoul: Gwangjang + Euljiro", color: "#34746e" },
    { day: 3, date: "2026-06-09", weekday: "Tue", title: "Seongsu cafés + Seoul Forest → Ikseon BBQ", color: "#3a5a9c" },
    { day: 4, date: "2026-06-10", weekday: "Wed", title: "Markets + seafood feast", color: "#6f4a7c" },
    { day: 5, date: "2026-06-11", weekday: "Thu", title: "Last bites & food souvenirs", color: "#b8893b" },
    { day: 0, date: "", weekday: "", title: "💡 Ideas / swap-in", color: "#8a8275" }
  ],
  stops: [
    // ---------- DAY 1 ----------
    { id: "pungnyeon",  day: 1, order: 3, time: "19:00", type: "bbq",
      name: "Pungnyeon Sutbul Galbi", name_ko: "연남 풍년숯불갈비", area: "Yeonnam-dong",
      lat: 37.5630532, lng: 126.9253417, cost_krw: 35000, place_id: "ChIJjZCiz-6YfDURXdhw0OBS_oo",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipM3MDTyrVdO7cyqBRP-tCsD7iQU5qlHQag0hokO=w800-h600-k-no",
      blurb: "First-night charcoal pork belly & galbi. 5.0★, family-run, real charcoal smokiness. Pair with soju.",
      reservation_status: "unlikely",
      slot: "dinner" },
    { id: "hongdae-chimaek", day: 0, order: 50, time: "", type: "bar",
      name: "BBQ Chicken & Beer (Hongdae)", name_ko: "BBQ치킨 홍대로데오점", area: "Hongdae",
      lat: 37.5523919, lng: 126.9213509, cost_krw: 25000, place_id: "ChIJB-rU19qYfDURFwGzBMnK7B8",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF5Wfet6j9nS6KQNrwLWbI_ZE89vvWK-a7gevF5QmteLm_8UVduDEFVFpElgy6nLx4EJIgxe4gGjw8hSCnKLExmfGPHcpxxHABN7_Keh2JMOeKy-jzNtL6O6x_IK9zJxoCDT-uPA4PSj_ru=w800-h600-k-no",
      blurb: "Chimaek nightcap — Korean fried chicken + cold beer, open very late. Any Hongdae chicken+beer spot works.",
      reservation_status: "unlikely",
      slot: "bar" },

    // ---------- DAY 2 ----------
    { id: "eulji-myeonok", day: 0, order: 51, time: "", type: "noodles",
      name: "Eulji Myeonok", name_ko: "을지면옥", area: "Euljiro",
      lat: 37.5736809, lng: 126.9885769, cost_krw: 14000, place_id: "ChIJgamxSgCjfDURXl5INU25Y88",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHWcNMT7h8D9KRC3Hhq1QNWYuORg1i7p2Q7IYsMDIgI5GpPJu9DntoFzUCsI-fz8rE7QIlr83uvt--3LfwwYoCQwzPPasoq9fnhPsRc5v6rIFMxrmgKkHDiHo_3L6HnpCa98yZLQ_oc8vKb=w800-h600-k-no",
      blurb: "Pyongyang-style mul naengmyeon (cold buckwheat noodles). CLOSED SUNDAYS, sells out — arrive by 12:30.",
      reservation_status: "unlikely",
      slot: "lunch" },
    { id: "gwangjang", day: 2, order: 2, time: "12:30", type: "market",
      name: "Gwangjang Market", name_ko: "광장시장", area: "Jongno",
      lat: 37.5700398, lng: 126.9996036, cost_krw: 15000, place_id: "ChIJm3V0fu2ifDURRJ8IMUijVtY",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH-TXd-qJ0hLQfDcLOR_s9wLjVRy-uzR7RfpW2iXOxiH9_PQQlKjMTa-YDU7M98ihE9Cv78qzEc_8AJ9guBbm85ugXz20w2AoJ5db2mYMJIVSRzIOoxJf0LBrIFOPASjRQxfmzlZX4OJ80=w800-h600-k-no",
      blurb: "Graze: bindaetteok (mung-bean pancake), mayak gimbap, yukhoe (raw beef), tteokbokki. Cash. Netflix-famous kalguksu too.",
      reservation_status: "none",
      slot: "lunch" },
    { id: "manseon-hof", day: 0, order: 52, time: "", type: "bar",
      name: "Manseon Hof (Nogari Alley)", name_ko: "만선호프", area: "Euljiro",
      lat: 37.5671948, lng: 126.991811, cost_krw: 20000, place_id: "ChIJn6hVByKjfDURx-hGevo1qx4",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGssxGNH9MTyH3T3jFBKJ4u0qyIn4SgR5e5N15CMuTTscpR0ZMOepmTH7d-LEfoM-R3Xr99IfFVYwp976gApkZRF0rfWbebpIs7_-eTFfxiCSvMNVEXKdPCYNzLS2do2v2lM2z2gvoJrY9X=w800-h600-k-no",
      blurb: "Euljiro beer-hall alley — dried pollack (nogari) + draft, plastic stools in the street. Vibe + beer, skip the chicken.",
      reservation_status: "unlikely",
      slot: "bar" },

    // ---------- DAY 3 ----------
    { id: "onion-seongsu", day: 3, order: 1, time: "10:00", type: "cafe",
      name: "Cafe Onion Seongsu", name_ko: "어니언 성수", area: "Seongsu-dong",
      lat: 37.5447328, lng: 127.0582091, cost_krw: 12000, place_id: "ChIJHb1ypJWkfDURb2d4XCjLluM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGbw0aYVH-sdUbfATXqONs0Od5RegVYrmzNMnAmNWEIRRDYiGXKjntZTXZGnmojNjNxJDH-VGPiK5KmawJuVGJLnEuW5Ndi6YDf7JWvJ0XRaJIAzZbQv7YT0kUsUrw093xHFaDDimlNk344=w800-h600-k-no",
      blurb: "Brunch in a brutalist former factory. Pandoro + salt bread. Go ~9–10am to beat crowds.",
      reservation_status: "unlikely",
      slot: "breakfast" },
    { id: "daelim", day: 3, order: 3, time: "15:30", type: "cafe",
      name: "Daelim Changgo", name_ko: "대림창고", area: "Seongsu-dong",
      lat: 37.5418384, lng: 127.0564636, cost_krw: 12000, place_id: "ChIJi_M445OkfDURBV_ePY2qCHo",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF9PMZkJSYL6hJxTIntemAcZNO1Yxp45UXYcMgQYGeIxTO_huAh5JyqnNQk0DXzVtLLpTgpCsi4x9XfAVSyd9k1wj3qhHnkG-RQ-jzpxquQ4xGepl6Xc6GHeYQjaxISqZN3ZdwP=w800-h600-k-no",
      blurb: "Giant red-brick warehouse gallery-café — the icon of Seongsu. Coffee + cake, cinematic industrial space.",
      reservation_status: "unlikely",
      slot: "cafe" },
    { id: "seoul-forest", day: 3, order: 4, time: "16:30", type: "park",
      name: "Seoul Forest Park", name_ko: "서울숲", area: "Seongdong-gu",
      lat: 37.5443878, lng: 127.0374424, cost_krw: 0, place_id: "ChIJK_b0UX2jfDURmkYPvmWYm90",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGTEBgUkQU-_V8wPmooQlejFVknGSjDzFwT7tahrZuHrkepXtTdpuw-K9tcdGeGnKVX-DtevG85Bux5X0iBV9wAZ0xWhm515DcEtd2VDwTTgZP0QaWgzLfHuLvQsYONQCk3M67lyw=w800-h600-k-no",
      blurb: "Optional easy stroll to walk off the coffee. Relaxed, not touristy — your one bit of green.",
      reservation_status: "none",
      slot: "sight" },
    { id: "gowoondon", day: 3, order: 5, time: "19:00", type: "bbq",
      name: "Gowoondon (Ikseon-dong BBQ)", name_ko: "고운돈", area: "Ikseon-dong",
      lat: 37.5730622, lng: 126.9899923, cost_krw: 28000, place_id: "ChIJJawtZQCjfDURYKP2MnwsfQk",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipPA3ggQCy5N9Y0fIiX6NqiUUgviWxjydUt4E7RO=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/", reservation_status: "needed",
      blurb: "Hanok-courtyard pork BBQ. 4.9★. Fills fast — arrive ~5–6pm or book via Catch Table. They fry rice/noodles for you at the end.",
      slot: "dinner" },

    // ---------- DAY 4 ----------
    { id: "tongin", day: 4, order: 2, time: "12:00", type: "market",
      name: "Tongin Market (coin dosirak)", name_ko: "통인시장", area: "Seochon",
      lat: 37.5807649, lng: 126.9706756, cost_krw: 8000, place_id: "ChIJYxd6fL6ifDURy7wm894BUcQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH-VoHyhUy0Ol6O2te7kJdMahoGsvv8n-NfOfeB9xhbMlL---ZoBfG_KnmnT3CmadKrqoDekp7X9iluEGZ8F0f3rjJnKrmt8hVRtPXjUP2njIvmukA-jJYPs6cTj17T1xXCyDiY5KowbRs=w800-h600-k-no",
      blurb: "Buy brass coins, fill a lunch tray from the stalls. Fun and cheap. Closes ~5pm.",
      reservation_status: "none",
      slot: "lunch" },
    { id: "tosokchon", day: 4, order: 3, time: "13:30", type: "soup",
      name: "Tosokchon Samgyetang", name_ko: "토속촌 삼계탕", area: "Seochon",
      lat: 37.5777786, lng: 126.9715909, cost_krw: 20000, place_id: "ChIJb5OOGL6ifDURU29ID3t8aOA",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHj6Xu3B1g5hgTJSLwSHAIMmij_j5SX8WcN447mwinTcfOLn4USV_806KRsGbqQTrhHBy3Gcsn35xEHSs4wWoRnMn38lgDUu2YSMP2VGWHkpBfxsLZbfTkGxTOU7H7EHde5kEtHQu66Rm6l=w800-h600-k-no",
      blurb: "5-min walk away — Seoul's famous ginseng chicken soup. Do instead of (or after) Tongin for a sit-down.",
      reservation_status: "unlikely",
      slot: "lunch" },
    { id: "noryangjin", day: 4, order: 4, time: "18:30", type: "seafood",
      name: "Noryangjin Fisheries Market", name_ko: "노량진수산시장", area: "Noryangjin",
      lat: 37.5149717, lng: 126.9386342, cost_krw: 50000, place_id: "ChIJOTEaKmiffDURNTst1Jzcm_c",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFoM2OmUrwDpW2KutU8vDjA7RPdGZICzMCcxPaNZFH4iA5lGTtqKrY7TK2yCua0ozPOk17EWnkRx8jOiUnK5DYF4qAPZKU5yBIPYgGYUXg-iqeMHgAdsaxNVTo-A-tmX2he2NRRmBXjwVVe=w800-h600-k-no",
      blurb: "Pick king crab/abalone/sashimi/live octopus downstairs, AGREE PRICE FIRST, eat it cooked upstairs. Cash. The big one.",
      reservation_status: "none",
      slot: "dinner" },

    // ---------- DAY 5 ----------
    { id: "london-bagel", day: 5, order: 1, time: "09:00", type: "cafe",
      name: "London Bagel Museum (Anguk)", name_ko: "런던베이글뮤지엄 안국점", area: "Anguk / Bukchon",
      lat: 37.5791826, lng: 126.986152, cost_krw: 12000, place_id: "ChIJKw66zRCjfDURuaw9qYPdI-k",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGYkxb5uafl7vpcRi319FEjpnDxybM-WdQpGXeBqekCzRh2Q_AAwchxNcMN0abgCg1JSrfJs71vO_sc1plbPkf_ApzCrAkTtcEC8OJqN7fs86RjU_VqJH04rPIVL2mx19IwEHsIaOLeTaHP=w800-h600-k-no",
      reservation_url: "https://app.tablemanager.io/", reservation_status: "needed",
      blurb: "Open-run bakery — get on the queue app early, or arrive ~8:30am. Potato-cheese & Bricklane bagels. Onion Anguk is 2 min away.",
      slot: "breakfast" },
    { id: "myeongdong", day: 5, order: 2, time: "", type: "market",
      name: "Myeongdong Night Market", name_ko: "명동 야시장", area: "Myeongdong",
      lat: 37.5616685, lng: 126.9858438, cost_krw: 15000, place_id: "ChIJqb-ne_CifDURR-yH8a3sjXM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH1FH1Gk1_Vi-S-oV7wTJIVSNTEI6ZbwfCSCang9xK_AACIN7Vd1MaPIzF3zFKYiDFI9Kgusr7G1HJ8hVdz48asjcwt7F8lr64ypgxbf_4tt8cOLNWIfnegmpKUb9vGOrmJ5W2zUozxtZ4p=w800-h600-k-no",
      blurb: "Late-flight option: street-food crawl (tornado potato, hotteok, egg bread) + edible souvenirs. Stalls ~5pm+.",
      reservation_status: "none",
      slot: "snack" },

    // ---------- IDEAS / SWAP-IN (day 0) ----------
    { id: "onion-anguk", day: 0, order: 1, time: "", type: "cafe",
      name: "Cafe Onion Anguk", name_ko: "어니언 안국", area: "Anguk / Bukchon",
      lat: 37.5776235, lng: 126.9865541, cost_krw: 12000, place_id: "ChIJLXL2BvijfDURmTrYFPQIGUc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEZ8XDN1sBLm4RNS4WXkpIPhjfJILKicwPXhgfhw34vjHgCzrFX-kYPben5TZcbnMnnIgU6CsmEZ0b11BdbEYeyZKMD6i8cZ5Z8_9S4cf2i4cRuAoHcT0A509N0I9ON3OnaKn9-WIqqiCDT=w800-h600-k-no",
      blurb: "Backup for the Day 5 bagel — hanok-courtyard café, famous pandoro.",
      reservation_status: "unlikely",
      slot: "cafe" },
    { id: "jeong-daepo", day: 0, order: 2, time: "", type: "bbq",
      name: "Jeong Daepo (Mapo BBQ)", name_ko: "정대포", area: "Mapo",
      lat: 37.541983, lng: 126.9511176, cost_krw: 30000, place_id: "ChIJqfTTJaeYfDURTvox_bUC6Mk",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGcLcQqUsuQzJdhodAy6QIScs0abIKhrp1clijvTd4WNd5512yMtjGiD4n6-dMDfWuq4Yhg62Ck0612_rVE59RA7Orwf1vQNqOIYCbR_qH9D0ATxp5EpYx-1vcbq43a3Ug23GGikihIOVV7=w800-h600-k-no",
      blurb: "Anthony Bourdain's Mapo charcoal BBQ — egg moat round the grill. Swap into any dinner slot.",
      reservation_status: "unlikely",
      slot: "dinner" },
    { id: "mingles", day: 0, order: 3, time: "", type: "splurge", michelin: 3,
      name: "Mingles", name_ko: "밍글스", area: "Cheongdam / Gangnam",
      lat: 37.5253386, lng: 127.0441452, cost_krw: 290000, place_id: "ChIJjXuM24mjfDURSwmouRnxNlM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGE6C8rxjQ0rmFGzxONberjbSVXY5M59rfXGinekid7vqyKJM_61V9P7rKhk1aeTT3f3v11W5fCMGJRX2-g6uskg2PsjbadrfHM1XIToGYKKys5N_6IH-IZFFdBkTEiXtqj0-uqIaGtsfSb=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mingles", reservation_status: "needed",
      unavailable: true,
      blurb: "★★★ Modern Korean tasting menu by Chef Mingoo Kang — the headline splurge. CLOSED Mon & Sun. Currently fully booked; see backups below.",
      slot: "dinner" },

    // ===== ⭐ MICHELIN-STAR BACKUPS (Seoul & Busan 2026) — Mingles replacements =====
    // cost_krw are rough per-person tasting-menu estimates — edit freely.
    { id: "jungsik", day: 3, order: 2, time: "12:30", type: "splurge", michelin: 2,
      name: "Jungsik Seoul", name_ko: "정식당", area: "Cheongdam / Gangnam",
      lat: 37.5226, lng: 127.0398, cost_krw: 280000, place_id: "",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGu_vHep9cYw2PBAsvQD3jquh5zkTcRHzocL07YO5vldzQ5CFI9W_vJB2HLzyy996Avxt1xUJNQWSl9-V8H7XscU2v4ZHwnqxFHlUw1NP-4AzvgkbMJMxG0BVljA0eDXVOLJuEp=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Jungsik", reservation_status: "booked",
      starred: true,
      personal_note: "Ashley you're cute 💛",
      notes: "💛 With Ashley · Booked Tue Jun 9, 2026 · 12:30 PM KST · party of 3 · 2F Hall (no phone listed)",
      blurb: "★★ Contemporary Korean — chef Yim Jung-sik's flagship, sister to the NYC outpost. CLOSED Sundays. Sleek, English-friendly. ✅ Booked for Tue Jun 9, 12:30 PM, party of 3, 2F Hall.",
      slot: "lunch" },
    { id: "onjium", day: 0, order: 21, time: "", type: "splurge", michelin: 1,
      name: "Onjium", name_ko: "온지음", area: "Hyoja-dong / Jongno",
      lat: 37.5824, lng: 126.9706, cost_krw: 180000, place_id: "",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAESVV00K9ONDswr-0YErjvG6Ycn-rH7rm5eKY4hpxmraGDcclvQVhkieT9M7jjY9x_37LyH5SAFIrhpAhczsgV8i-aU3eSr2Vk-tAtRt9CpvsWdLQvl3KtburMhSwSUA1ZQSSCkfQ=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Onjium", reservation_status: "needed",
      blurb: "★ Royal Korean cuisine in a quiet hanok, near Gyeongbokgung. CLOSED Sundays. Lunch only — a beautiful, restrained tasting.",
      slot: "dinner" },

    { id: "la-yeon", day: 0, order: 23, time: "", type: "splurge", michelin: 2,
      name: "La Yeon", name_ko: "라연", area: "The Shilla Seoul (Jung-gu)",
      lat: 37.5557646, lng: 127.0050866, cost_krw: 250000, place_id: "ChIJf8Lq1wSjfDURbuyVUM14Svc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGSzdVWTQVvEFprsHGL1GBPqcQjQrj0APQJwI4wtA_21giqyZS10YRlANdZx4KBLi4e-74-Noo4Cq1MdZeLURoOmn316J1mPGinYEVe0ckiPaGoAdzuNn9CEtmXHFDg4Z6KEswK27DLTHkb=w800-h600-k-no",
      reservation_url: "https://www.shilla.net/seoul/dining/viewDining.do?contentId=la-yeon", reservation_status: "needed",
      blurb: "★★ Korean, on the 23rd floor of The Shilla with Namsan views. OPEN DAILY (lunch+dinner) — a hotel restaurant, so often the easiest 2★ to book last-minute.",
      slot: "dinner" },
    { id: "mosu", day: 0, order: 24, time: "", type: "splurge", michelin: 2,
      name: "Mosu Seoul", name_ko: "모수", area: "Hannam-dong",
      lat: 37.5411532, lng: 126.9961548, cost_krw: 350000, place_id: "ChIJJeNdcbOjfDURCzyDecCVK7o",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEBwPzNcqHrre7Xxr3SkH7KPmlrxGTMoAO-wjzaSGxPeJ_hc5uSDF-io4gD0kVhcH4HJX6uHIIsnmolkqjnMdclkD0Wr5fp1sujv21OyrYEJTnzZT13sCYVrnnU6QqbiGjYYBBLPAqCvWWe=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mosu", reservation_status: "needed",
      blurb: "★★ Modern Korean by Chef Ahn Sung-jae — Seoul's most acclaimed tasting menu after Mingles. Dinner only, CLOSED Sun & Mon. Hardest to get; try anyway.",
      slot: "dinner" },
    { id: "alla-prima", day: 0, order: 25, time: "", type: "splurge", michelin: 2,
      name: "Alla Prima", name_ko: "알라프리마", area: "Gangnam (Hakdong)",
      lat: 37.5134138, lng: 127.0260405, cost_krw: 260000, place_id: "ChIJsdM8l_KjfDURobnSNkInVo8",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEG41qAh7Sk0ma4WOOvE5b8rep623KWJOFOMyUXdfBRDn9nTSh0VuLWxN4jjZtRtASKgWu04qQJtfc39FnfrGWUwJW2J6vBILZkHrM0LQvjtKeZs0-ur5ZUG3quG52voHv7nwRtT_TXLjyK=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Alla+Prima", reservation_status: "needed",
      blurb: "★★ Innovative/contemporary, bar seats over a busy open kitchen. CLOSED Tuesdays. Refined, French-leaning technique.",
      slot: "dinner" },
    { id: "soigne", day: 0, order: 26, time: "", type: "splurge", michelin: 2,
      name: "Soigné", name_ko: "스와니예", area: "Sinsa / Gangnam",
      lat: 37.5193295, lng: 127.0190326, cost_krw: 230000, place_id: "ChIJIU2RrnahfDURNvCJDhODupM",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH_F2xWh9iRDkUXLRIURvFcfiNP0s4T1PDVSpDnY4drNE5l0UUDN7O6MM8Qs9ywbeaiZo7-9qc2GPKviLDKRHlkcRp3a1Jt78ae1LTsnOIj8KkJorZIpckL-NLnq1b73fxyNZTu=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Soigne", reservation_status: "needed",
      blurb: "★★ Contemporary Korean-French, famous for its hanwoo. Calm minimalist room. CLOSED Sundays. Lunch is easier to book than dinner.",
      slot: "dinner" },
    { id: "kwonsooksoo", day: 0, order: 27, time: "", type: "splurge", michelin: 2,
      name: "Kwonsooksoo", name_ko: "권숙수", area: "Apgujeong / Cheongdam",
      lat: 37.5243775, lng: 127.0435589, cost_krw: 290000, place_id: "ChIJZ1-yoYijfDURvkRg_wdaQao",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGqwAtsFKU6aZvPZhSynrbX6QlJkgFj6S-o3iI2CzNvogdkNV2S0ATTnkd701_oenHuTv6gPK9KRG0g0c4EgQNuKHhmfmfEAiALb_mjRBCiDdWE6PFhy8AgqRiZRSJpauwbZl0=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Kwonsooksoo", reservation_status: "needed",
      blurb: "★★ Korean, deeply seasonal with a beloved kimchi cart and 45-year-aged soy. CLOSED Sun & Mon.",
      slot: "dinner" },
    { id: "mitou", day: 0, order: 28, time: "", type: "splurge", michelin: 2,
      name: "Mitou", name_ko: "미토우", area: "Cheongdam",
      lat: 37.5221974, lng: 127.0450306, cost_krw: 300000, place_id: "ChIJGZ6vIe2jfDURWOUsVCO94cA",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGrDY5RXI-bGkcFjDEHmncJYu636bR3XSSwfkcadejLWdc-DQXyMImtNGhKmOx-pN6j5ywgoe604WJ5lTsn7kJmGJaV9MdPUsU8nOyjdH0WyCjKm7YwcYvzkJ4Khxcsg9oOoeIh=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Mitou", reservation_status: "needed",
      blurb: "★★ Intimate Japanese kaiseki, two-chef counter. Dinner only, CLOSED Sun & Mon. Tiny — book the moment a slot opens.",
      slot: "dinner" },
    { id: "restaurant-allen", day: 0, order: 29, time: "", type: "splurge", michelin: 2,
      name: "Restaurant Allen", name_ko: "레스토랑 알렌", area: "Gangnam (Teheran-ro)",
      lat: 37.5036006, lng: 127.0418041, cost_krw: 260000, place_id: "ChIJQ-Y88belfDURrUsKUS6HMVY",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG9N5eDlVJyZz7gynMaYroB9gA7ZLrJonwjAdTPgJdhVIOl1xEC0zntmvhe8BD5CIWi3Vp0Z2j9IftOGAvv2y4ygVlQrZYx7ufh0-lxW_Cj70zRsFcc3QIxiNcJZCo8tfy9RwE=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Allen", reservation_status: "needed",
      blurb: "★★ Contemporary/French using Korean farm produce, seasonal menu. CLOSED Sun & Mon. Generous, filling courses — a crowd favorite.",
      slot: "dinner" },
    { id: "sosuheon", day: 0, order: 30, time: "", type: "splurge", michelin: 2,
      name: "Sosuheon", name_ko: "소수헌", area: "Jung-gu (Malli-dong)",
      lat: 37.5529456, lng: 126.9634031, cost_krw: 380000, place_id: "ChIJ6fwnPgCjfDURRK3JXHKApos",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG82IFmZhRaBRQ8gG2DC8wXdM3h3sgIQl3IZR6ayEEMFrVWbEh08qVByHp2oiqG7u6Ae06OGiMSh9y8BXapTlTxFtiF9PZIce3jGTSkZa7sScAMOUBAFOs6rLgm400eIjRHlEuO=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Sosuheon", reservation_status: "needed",
      blurb: "★★ Sushi by Chef Park Kyung-jae in a renovated hanok inside a park. Reservation-only and notoriously hard — long-shot backup but worth a try.",
      slot: "dinner" },
    { id: "evett", day: 0, order: 31, time: "", type: "splurge", michelin: 2,
      name: "Evett", name_ko: "에빗", area: "Gangnam (Dosan)",
      lat: 37.5233759, lng: 127.0362133, cost_krw: 260000, place_id: "ChIJTaVjWi6hfDURVegqLOB9oSs",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHenaN9tIjz4LooC9mdlPnpBaRKRSEByIraKBeBkzpa7-REi59CuaCKuvSFA6lUBUnQYCGFPMo18F3lFHrAsP0IvRddEFOaD-h6JDzI89wanQCEUXSo_sXXAiH_ne7JvN2oZpLXmg=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Evett", reservation_status: "needed",
      blurb: "★★ Inventive Korean-meets-Australian by Chef Joseph Lidgerwood, with a fun kitchen tour. CLOSED Sun & Mon. English-friendly; juice pairing is great.",
      slot: "dinner" },

    // ===== 🍢 STREET FOOD (cool picks) — day 0 =====
    { id: "bamdokkaebi", day: 0, order: 32, time: "", type: "streetfood",
      name: "Seoul Bamdokkaebi Night Market (Yeouido)", name_ko: "여의도 밤도깨비 야시장", area: "Yeouido Hangang Park",
      lat: 37.5308271, lng: 126.9283536, cost_krw: 12000, place_id: "ChIJYxvcuRiffDURjo90ImhrJvg",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF8RIrKpG_TGBZ7VBJWrcgOetLfgWIlPb106vedBBIpZw7uqWuv5CbkhOJRd6R4NNN8EZmY1qqC19XYLpwgF4_E5B8azAS8rsO-w1pT_PHvigsBDk3D3iy0uh1IDtj-1C9cYjWh=w800-h600-k-no",
      blurb: "⭐ THE cool one: food trucks along the Han River — eat by the water with a picnic-blanket crowd. WEEKENDS ONLY & seasonal (roughly Fri–Sun eves, spring–autumn). On this trip that's Sun Jun 7 — CHECK the current Hangang/Seoul night-market schedule before counting on it.",
      reservation_status: "none",
      slot: "snack" },
    { id: "jongno-pocha", day: 0, order: 33, time: "", type: "streetfood",
      name: "Jongno 3-ga Pocha Street", name_ko: "종로3가 포장마차 거리", area: "Jongno",
      lat: 37.5702277, lng: 126.9922392, cost_krw: 20000, place_id: "ChIJlcTjXMmjfDURY4e90Feo_dw",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHfQ_pkNxVjrgVwlUKGlyAjYIF8j1Kz37zhr_k8oaH12BZBp9EJfzixFUVPg6A8zFclrM4SEEePJNKSK7qvkH6l2qm7Apvb9UY9tC4DSMU7pJr_ZiMs3dv2FrGkdkWJlXRb-MINwrkgNS0=w800-h600-k-no",
      blurb: "Pojangmacha — orange-tent street stalls at night: seafood pancake, eel, oden, soju, friendly ajummas. Street food + a drink in one. Great late-night near Euljiro/Ikseon (Days 2–3).",
      reservation_status: "none",
      slot: "snack" },

    // ===== 🍸 BARS (nightcaps) — day 0 =====
    { id: "zest", day: 0, order: 34, time: "", type: "bar",
      name: "Zest", name_ko: "제스트", area: "Cheongdam",
      lat: 37.5252611, lng: 127.0407780, cost_krw: 55000, place_id: "ChIJ9eN6-_GlfDUR5SGWDB7YNkw",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEO_M4c2KwQs7zI3RlUPqtUCtg5Ev5g3_DVZTYF6mJWVvW6608dTHgU67xKjJuWZ0l2fJUgCzUhijst_-jftzz0_-znYRsvCtpUEaAZ6cZfYiPUSDIdZTbUsQFnPDDfq5DuPgHFGQ=w800-h600-k-no",
      reservation_url: "https://www.catchtable.co.kr/en/search?keyword=Zest", reservation_status: "needed",
      blurb: "#2 on Asia's 50 Best Bars 2025 — sustainability-driven cocktails, every drink ~₩26k. Tiny & busy; reserve ahead or chance a walk-in. Open daily.",
      slot: "bar" },
    { id: "le-chamber", day: 0, order: 35, time: "", type: "bar",
      name: "Le Chamber", name_ko: "르챔버", area: "Cheongdam",
      lat: 37.5262177, lng: 127.0410396, cost_krw: 60000, place_id: "ChIJ639qa3ikfDURlcK_PQa7PbQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFVuc_vQwI8TiU9bpCw2k0uLQnEZuk-QNY-qZprJdOCdAsytCRLdiqGF6XZ4cHoWo57qAGkZaED2S_DkyG-s68gzjy9EeSd2u7NnlT-CykERTSYbv0RFWuLLMDWzZd9Qp92AbQbpb623bg=w800-h600-k-no",
      blurb: "Bookshelf speakeasy — push the right book to get in. Grand-piano glamour, Asia's/World's 50 Best. Open daily, very late.",
      reservation_status: "needed",
      slot: "bar" },
    { id: "bar-cham", day: 0, order: 36, time: "", type: "bar",
      name: "Bar Cham", name_ko: "바참", area: "Seochon",
      lat: 37.5791709, lng: 126.9703851, cost_krw: 45000, place_id: "ChIJxWShw9-jfDURS80cyKrrVI4",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipOgzaVroL6GgFco2rzkUwhp2JyT2RYuegUO0fit=w800-h600-k-no",
      blurb: "Cozy cabin bar, cocktails built on Korean ingredients & regions. World's & Asia's 50 Best, famously warm service. CLOSED Tuesdays. Right by Day 4's Seochon.",
      reservation_status: "needed",
      slot: "bar" },
    { id: "charles-h", day: 0, order: 37, time: "", type: "bar",
      name: "Charles H.", name_ko: "찰스 H", area: "Gwanghwamun (Four Seasons)",
      lat: 37.5705573, lng: 126.9754314, cost_krw: 60000, place_id: "ChIJfZLLbCOjfDURJv2oIh07atc",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG88O2yer2aqC8VVa8M58CJBUiyLLVh5sytJzGvX0ggC3KgTN1eyIsDP7RIWB7kUGT0md95Cvf4PSQCDcr0wb1uUCmCM24OZvNgVY0sLrCUX8K7cXEga5w_wIU-6KrWONpDmsXvtAIhhs44=w800-h600-k-no",
      reservation_url: "https://www.fourseasons.com/seoul/dining/lounges/charles_h/", reservation_status: "needed",
      blurb: "Refined hidden speakeasy inside the Four Seasons — hyper-local Korean cocktails + great bar food. Central, open daily. Easy nightcap near Days 2/5.",
      slot: "bar" },
    { id: "saeseoul", day: 0, order: 38, time: "", type: "bar",
      name: "Saeseoul", name_ko: "새서울", area: "Ikseon / Jongno",
      lat: 37.5728113, lng: 126.9898352, cost_krw: 40000, place_id: "ChIJ1x9w99CjfDURbbBhFKdp_8Y",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipN5mwl9AxOXYMMq6QA5diYojfWzSMyEMMl7ZsP2=w800-h600-k-no",
      blurb: "Hidden bar above a retro arcade with a rooftop city view and playful drinks (try the 'Pacman'). Open daily — perfect nightcap after Day 3's Ikseon BBQ.",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "slow-brew", day: 0, order: 39, time: "", type: "bar",
      name: "Slow Brew Pub (Neurinmaeul)", name_ko: "느린마을 양조장", area: "Gangnam / Seocho",
      lat: 37.498097, lng: 127.0252657, cost_krw: 30000, place_id: "ChIJHbhgd1mhfDURfkpQ0mGQ6sQ",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAExXvm3hLOro8FmmA57N_u0rQZ7iqcQ1D0Js8ZT4DuZtwYekZ3y5V6IsGjbD5Qavf6dIg3CBUtwriHeXfIxCALP14N16_N7jUkl9PJtsixf2hG2YSQDzLWMf3s4uJkz4jB2S7YbClLFAvsR=w800-h600-k-no",
      blurb: "Makgeolli (rice wine) by the season + jeon pancakes in a modern brewery pub — the traditional-drinking option. Open daily.",
      reservation_status: "unlikely",
      slot: "bar" },

    // ===== 🥩 PREMIUM HANWOO BBQ — day 0 =====
    { id: "insaeng-hanwoo", day: 0, order: 40, time: "", type: "bbq",
      name: "Insaeng Hanwoo", name_ko: "인생한우", area: "Majang / Seongdong-gu",
      lat: 37.57011, lng: 127.0381874, cost_krw: 60000, place_id: "ChIJh5LfCFWjfDURiQ4ty7V9Gqk",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE0vCPzoUUo36cPfRwOnDjekE3uv1Slv3TeZ4zVlLbtlulaaDlV6pHPa3a7c_EDDapvKFGO0K-Y8SkS9cDCSsY7U7CYscjeJ7WU0_PjaSpzaoLbqY9ZuBxwxOD26NCSteapf0OGUFD_0eD1=w800-h600-k-no",
      blurb: "Premium Korean beef (hanwoo) — 1++ grade and 14-day wet-aged, at famously fair prices for the quality, near Majang meat market. Pick your cuts (kkotdeungsim/ribeye is the move); it barely needs the grill. Open daily (break ~2–4:30pm). It's in Seongdong-gu, a short hop from Seoul Forest/Seongsu — a great swap for Day 3's dinner if you'd rather not backtrack to Ikseon.",
      reservation_status: "unlikely",
      slot: "dinner" },

    // ===== 🍸 ONE BAR PER NIGHT (pre-placed nightcaps) =====
    { id: "night1-seventeen", day: 1, order: 4, time: "23:00", type: "bar",
      name: "Seventeen Birthday", name_ko: "세븐틴벌스데이", area: "Hongdae",
      lat: 37.5501207, lng: 126.920202, cost_krw: 35000, place_id: "ChIJXw_f0heZfDUR09E8z7UQB8s",
      blurb: "Night 1 nightcap — cozy, foreigner-friendly Hongdae cocktail pub (4.9★), games & chill vibe. Open late daily. Walk from the chimaek.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHZFfkM7EnBoTuf8-rZsncGwOUMPj3hIoNa3jt0MeoTsRlqk_uvVTNyZSxJwIehROnX--BZj3ZeKYoVBv9V6XFxp-XRRjZPoRMwgUyM0FO3mVOXdSdexcI8CcPoYX53mUfs05r9wlGuxd6l=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "night2-anotherlv", day: 2, order: 4, time: "22:30", type: "bar",
      name: "AnotherLv.", name_ko: "AnotherLv. 을지로", area: "Euljiro 3-ga",
      lat: 37.5656629, lng: 126.9912504, cost_krw: 40000, place_id: "ChIJQ4QPT_qjfDUR_CtRnA6uRmw",
      blurb: "Night 2 nightcap — Euljiro rooftop bar a minute from Nogari Alley, order by tablet. Open daily. Cocktails + good bar food upstairs.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFcb1G-hwzuy9DZH764aK-mtqYA-FuQ9xqfBFqBMpxi8bQ0QOQ816ROOrH6gsMy5NyLkPQ5Hx9I4kdprJUBCP6OF5LmAG3eV9oGYXTdirL2K71f7Q6tCPq-Ta-tVIgwY_FDdpQSQw=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "night3-cinderella", day: 3, order: 6, time: "22:00", type: "bar",
      name: "Cinderella Bar", name_ko: "Cinderella Bar", area: "Seongsu-dong",
      lat: 37.5461793, lng: 127.0548466, cost_krw: 45000, place_id: "ChIJF8iSZ7GlfDURDlfgs5z2QHw",
      blurb: "Night 3 nightcap — playful Seongsu cocktail bar (4.9★), drinks served in glass slippers. Closed Mon, but Day 3 is Tue so you're fine.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGlYBtjQ49a4s0HMh6T-T1G1POAXvDBl8SsWjLKKjxMdKDS39z5H5cTb3w_r1T7zB-f0PW28-EATu9Lbv8BGlJUNm0nc9lznaLHGRm5aYgAPLkc72qnlg8GOrYi3PGYOM3Yn1tjeqKvOmA=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "night4-pineco", day: 4, order: 5, time: "22:30", type: "bar",
      name: "Pine&Co", name_ko: "파인앤코", area: "Gangnam (Seolleung)",
      lat: 37.5262836, lng: 127.0370432, cost_krw: 45000, place_id: "ChIJrfK6ThqjfDURFv6cbuVlLlY",
      blurb: "Night 4 nightcap — intimate hidden Gangnam cocktail bar (4.7★), open daily. Pairs with a Gangnam splurge dinner; swap if you stay central.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEax3aMv21RntpxO7crwZX08bCCFnW7sfGMqB8F1ntfxhHmOipf2tlC-QS1_u7STnv0RJtLYJNzkzAo7Q1dsBuNwGbn8iuNWBvVy740zkkyi_bvoJg8QJsD9IlsowVjb1nEa-x7Pq0hm8X6=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "night5-cobbler", day: 0, order: 53, time: "", type: "bar",
      name: "Cobbler", name_ko: "Cobbler", area: "Seochon / Gwanghwamun",
      lat: 37.5753045, lng: 126.9709071, cost_krw: 45000, place_id: "ChIJEarhOpSifDURRuiCHsOFkOQ",
      blurb: "Night 5 nightcap — no-menu craft cocktails in a hanok near Anguk; just tell them what you like. Open daily. (Only if you've got a late flight.)",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGGDFnWAH9G0mP-PC5kb8xkDwSzHyIPFEbEKn_OJIly7seJNWHm14_CMAtcKfDpInAjRn8PUQi0U3DEbjHDbkG4dxGHggiTALFTYpP1dhmK7z1AwAtC4Rxif1S8pStExqwXbM079g=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },

    // ===== 🍸 MORE BARS TO SWAP IN — day 0 =====
    { id: "southside-parlor", day: 0, order: 41, time: "", type: "bar",
      name: "Southside Parlor", name_ko: "Southside Parlor", area: "Itaewon (Noksapyeong)",
      lat: 37.5370925, lng: 126.9870429, cost_krw: 40000, place_id: "ChIJXZvbb0iifDURdSMUpMDYfTI",
      blurb: "Itaewon rooftop — Texan cocktails + food, darts, easy English. On Asia's 50 Best radar. Open daily (earlier close Sun).",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFu2fIVV4wJWfQFPCkC1Uf_P_AE9gAbCqdeETC98u-mnzYgXzT1GEeBXrBFDM8FvsnVQtrL6c2Xx4zE4hplcYYxoYr_AmgY7bd1By9xnqWaNp5ccIm_vTEshhTzmzTS6Qr3un2QBw=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "alice-cheongdam", day: 0, order: 42, time: "", type: "bar",
      name: "Alice Cheongdam", name_ko: "Alice Cheongdam", area: "Cheongdam",
      lat: 37.5266874, lng: 127.040951, cost_krw: 55000, place_id: "ChIJ1SQnb3ikfDURcbiz6NFB5h0",
      blurb: "Alice-in-Wonderland speakeasy behind a flower shop — whimsical drinks, ₩10k cover w/ snacks + welcome cocktail. Open daily; reserve.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFTAV3VerG08yXXLtz4yefzFGzyfFFOJ5USODnP47_uGvXT11bcGFbiGIf4JXvEsMrvpmJYcMRW9tw9vJAxMrLvwqatnMI6jgQBqj5dSZj1cLeqgOANV4U6tuTfbBqbL18ug3E6PD17-iA=w800-h600-k-no",
      reservation_status: "needed",
      slot: "bar" },
    { id: "jean-frigo", day: 0, order: 43, time: "", type: "bar",
      name: "Jean Frigo", name_ko: "Jean Frigo", area: "Euljiro / Toegye-ro",
      lat: 37.5635637, lng: 127.0080518, cost_krw: 45000, place_id: "ChIJ54Gv9BejfDURHPT9fNTfmXY",
      blurb: "Hidden bar you enter through a fridge — fruit-forward cocktails, 4.8★. CLOSED Mondays. Fun ordering gimmick.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHKWdBzAOrVsNW9lYzNSz3qoTxPIJkPjRCcrr25uoIlg7T8MD-GYy6xsye9Z2YsWy_E5yVtEGSpEfL9cz4WdOvstodBOSi3iTWbB4nub2sEDV7XPjHku9_6Fgpb5jfnOVSR_v_I6gV2M_7X=w800-h600-k-no",
      reservation_status: "unlikely",
      slot: "bar" },
    { id: "magpie-itaewon", day: 0, order: 44, time: "", type: "bar",
      name: "Magpie Brewing (Itaewon)", name_ko: "맥파이 이태원", area: "Itaewon",
      lat: 37.5393931, lng: 126.9875108, cost_krw: 25000, place_id: "ChIJyYpst0iifDURBTGdpA0-huQ",
      blurb: "Beloved Korean craft-beer taproom — go the IPA + seasonals, outdoor seating. CLOSED Mon & Tue.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGElvr4WTDakNtd6VnG2kS9nEs4EAEPOVQWJTyTFL-VVaAFryB9n5SSMFijgEFu8PtcWvmsgvOWLjyPvDkD_6LqbdnNg-ESJstN2WJSiALjdruSO8yl916dlm9wFLpZ3S9dBO97=w800-h600-k-no",
      reservation_status: "none",
      slot: "bar" },
    { id: "mikkeller", day: 0, order: 45, time: "", type: "bar",
      name: "Mikkeller Bar Seoul", name_ko: "Mikkeller Bar Seoul", area: "Sinsa / Gangnam",
      lat: 37.520831, lng: 127.0239105, cost_krw: 35000, place_id: "ChIJ6UWloeyjfDUR3dlrnIm_uZE",
      blurb: "Danish craft-beer institution — flights of 6, plus Korean micro-brews & pizza. Pricey but reliable. (Check current hours.)",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEKNFXTO5XJ_Ou4W2EYAtm-e175Jb_FBAiT8OaCK-xqItzzvo9TrBgQE2cFvAtSWu-SY26ftReJDFtglrscsgm8e0iGt4bZ6wV5Ao7T6s8mphj1dT_tgENSpzjhHLYLF7LKfEdR=w800-h600-k-no",
      reservation_status: "none",
      slot: "bar" },

    // ===== Breakfast/Lunch additions placed into the plan =====
    { id: "dot-blanket", day: 1, order: 1, time: "09:30", type: "cafe", slot: "breakfast",
      name: "Dot Blanket Brunch Cafe", name_ko: "도트블랭킷 연남", area: "Yeonnam-dong",
      lat: 37.5596088, lng: 126.9250633, cost_krw: 18000, place_id: "ChIJBeOGKgCZfDURnbrVMgzn0LI",
      reservation_status: "unlikely",
      blurb: "Day 1 breakfast — cozy Yeonnam brunch (5.0★): open-faced sandwiches, pastas, good coffee. Opens 9:30, daily. (Skip/shift if you land late.)",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGPQnmYDuBdPQWT_9Ot0QcYBr_y8q4-i7Erm1igmb4P39u4T-RVX8PUG_ocxmcYw4BmozbNdobnlfK5XBDERzCAAT6PVvePUFMpGQkeo7Z-1qvLZUmjhQ1pp9wl4z4yCdltt9d_6LsrU_5a=w800-h600-k-no" },
    { id: "osowa-kalguksu", day: 1, order: 2, time: "13:00", type: "noodles", slot: "lunch",
      name: "Osowa Kalguksu (Seogyo)", name_ko: "어서와칼국수보쌈", area: "Hongdae / Seogyo",
      lat: 37.5548128, lng: 126.916441, cost_krw: 12000, place_id: "ChIJ_z7DXgCZfDUREIygdVW-dho",
      reservation_status: "unlikely",
      blurb: "Day 1 lunch — springy handmade kalguksu (knife noodles) + bossam, foreigner-friendly. Opens 10, daily.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF0jCP_gGjUe8UF6Vud0bkKihEpmZrHBwL-Ph-cREe7_rflg0Cz2GqCjj4wVbdZ8Ljn9Oaex23jGwpN3jMHoVMp6UwvcXpQnBaB8zPbQPTqD9rgnfAHzEfR-cyKirSAkTTYu86UxBp-j62N=w800-h600-k-no" },
    { id: "cheongjinok", day: 2, order: 1, time: "08:30", type: "soup", slot: "breakfast",
      name: "Cheongjinok", name_ko: "청진옥", area: "Jongno",
      lat: 37.5716988, lng: 126.9793981, cost_krw: 12000, place_id: "ChIJyfkL8-uifDURGjR9tuiIbSo",
      reservation_status: "unlikely",
      blurb: "Day 2 breakfast — haejangguk (hangover soup) since 1937, opens 6am. The classic Korean morning bowl, central in Jongno.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH50meQQckoG2Qc63ncWPpj2s-LpSr43wu3bTa5EBP7UCVRzbfcJQ7uXIdpCkdbfVll37KHvVdqqZYyA7b5uXQnWWIFv73HAReBMxPo0WVtidL8v-W0MQDO4KZem8jSuf8aHVLY=w800-h600-k-no" },
    { id: "daechang-euljiro", day: 2, order: 3, time: "19:00", type: "bbq", slot: "dinner",
      name: "Yangmiok (Euljiro Daechang)", name_ko: "양미옥", area: "Euljiro",
      lat: 37.5667845, lng: 126.9911758, cost_krw: 35000, place_id: "ChIJP6tF_v6jfDURtR0Lo_GDfPg",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEI6_IqdENciMc_KyV15QfiMkk1OKX54xyRi_NVadDc8B0uzlf69py4UUN_Bdvi_YHdQUC3f1ii6QeyZWUdYekqQ78qMXjLXzh3U5rGxCiQrbbkG3xqIai8Ufj_EKmP8TtA84dbR9H1xdnv=w800-h600-k-no",
      reservation_status: "unlikely",
      blurb: "Day 2 dinner — Euljiro daechang (grilled beef intestine) institution; pair with soju + cold noodles. Open daily." },
    { id: "schedule-seongsu", day: 0, order: 60, time: "", type: "other", slot: "lunch",
      name: "Schedule Seongsu", name_ko: "스케줄 성수", area: "Seongsu-dong",
      lat: 37.5444617, lng: 127.0554135, cost_krw: 20000, place_id: "ChIJD502OU6lfDURetD_VMLkRnA",
      reservation_status: "unlikely",
      blurb: "Lunch idea — trendy Seongsu Italian (4.8★): garlic baguette, gamberi rose pasta. Right by the cafés and Cinderella Bar. (Bumped from Day 3 by the Jungsik booking; drag back in if plans change.)",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipMoYovICA9tICKc0sAvaS3Xin1gHizSIds6Mzc1=w800-h600-k-no" },
    { id: "la-farina", day: 4, order: 1, time: "09:30", type: "cafe", slot: "breakfast",
      name: "La Farina Bagel", name_ko: "라파리나 베이글", area: "Seochon",
      lat: 37.5799307, lng: 126.9715311, cost_krw: 12000, place_id: "ChIJRzxu5C-jfDURAyE109aF5RE",
      reservation_status: "unlikely",
      blurb: "Day 4 breakfast — pillowy-chewy bagels in Seochon, opens 9:30. A short walk from Tongin Market. Get the ham & French butter.",
      image_url: "https://lh3.googleusercontent.com/geougc/AF1QipPdxEVEdkc2X_0uB-5hMyx_r_5X12WOSv9ro0J-=w800-h600-k-no" },

    // ===== More breakfast / one lunch options — day 0 =====
    { id: "isaac-toast", day: 0, order: 46, time: "", type: "cafe", slot: "breakfast",
      name: "Isaac Toast (Myeongdong)", name_ko: "이삭토스트 명동", area: "Myeongdong",
      lat: 37.5608265, lng: 126.9834404, cost_krw: 6000, place_id: "ChIJs66nIfGifDURFh-MeU01bbU",
      reservation_status: "none",
      blurb: "Cheap, fast Korean griddled-toast breakfast (ham-egg-cheese + sweet 'Isaac sauce'). Opens 7am. CLOSED Sundays. Mostly takeaway.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG94jdZhx5-AbF-NStSFK1MObPSqoGczZI-Ii3OBlf1yLjcnUqoRrMncj5qo9OCdV259pUIKNX4LudyKnGQR8XtCpJsgdDU2wpKi5FhPXmTDCWj2GahV_JcwigUFL4VXhCCPj92CCX1MTxU=w800-h600-k-no" },
    { id: "bonjuk", day: 0, order: 47, time: "", type: "soup", slot: "breakfast",
      name: "Bonjuk (Myeongdong)", name_ko: "본죽 명동점", area: "Myeongdong",
      lat: 37.5614867, lng: 126.9853997, cost_krw: 13000, place_id: "ChIJV_IRYvCifDURAjR3Sl7eIWM",
      reservation_status: "unlikely",
      blurb: "Gentle Korean breakfast — juk (rice porridge), e.g. abalone or ginseng-chicken. Opens 9am. CLOSED Sundays. Easy on a tired stomach.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGOmf7LQz64qxPNXGvYBzKDmm701VOLTREuhFZI0tGI16avN-dvVrCmaDVW2J8bryC-zKvnYcnvu9UnVI5gENi8fFRWgnC3rhMC51qS1CrIp3adh23EDnYULpTU86UlR9m0tep9YyhRDi8=w800-h600-k-no" },
    { id: "tartine-hannam", day: 0, order: 48, time: "", type: "cafe", slot: "breakfast",
      name: "Tartine Bakery (Hannam)", name_ko: "타르틴 베이커리 한남", area: "Hannam",
      lat: 37.5344222, lng: 127.0084676, cost_krw: 14000, place_id: "ChIJr0fz-RGifDUR9Q031ZkC8cw",
      reservation_status: "unlikely",
      blurb: "SF-style sourdough, croissants & breakfast sandwich in Hannam. Opens 8am, daily. Best bread-breakfast in the city.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEAJs_t74cFaUllw31-cNutMG_auCInK4lknVyJKA1h86RDq-aCrm9EYHfqiTiGPCfoWQ-qwcQCd_0Gz9czEUK7rngUZU_EidARtmpz8negr9zIS7b1eQ1HVXfnjKDpSpezkg9G3g=w800-h600-k-no" },
    { id: "jinju-house", day: 0, order: 49, time: "", type: "noodles", slot: "lunch",
      name: "Jinju House", name_ko: "진주회관", area: "Yeouido / City Hall area",
      lat: 37.520782, lng: 126.9269161, cost_krw: 12000, place_id: "ChIJg3mO-z2ffDURxBvzNdq99p4",
      reservation_status: "unlikely",
      blurb: "Bonus lunch — famous kongguksu (chilled soy-milk noodles), perfect for June heat, + mandu. Opens 10. CLOSED Sundays.",
      image_url: "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGOKHHgsjXuP5xx9cMJLmDaVPUZGetnaHu8iIo6r3beki2lfXJSNKtW1vfqnNT88akdoP70cmGzg2KDkIirbOtKbtrNj_KG3HViS3_B-HURkgZINvGTZ6U-mHmHhqWfA9oIIlpobg=w800-h600-k-no" }
  ]
};
